package com.example.seleniumGUI;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
public class TranslateGoogle {
    private WebDriver driver;
    JavascriptExecutor js;
    String input;//the word to be translated
    String translate;//the expected word
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","src/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;;
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void translate() {
        input="la pizza margherita è buona";
        translate="the margherita pizza is good";
        driver.get("https://www.google.com/search?q=translate&rlz=1C1GEWG_itIT949IT949&oq=translate+&aqs=chrome.0.69i59j0i131i433i512j0i433i512j0i131i433i512l2j0i512l2j0i131i433i512j0i512l2.3796j0j15&sourceid=chrome&ie=UTF-8");
        driver.manage().window().setSize(new Dimension(1058, 682));
        driver.findElement(By.cssSelector("#L2AGLb")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector(".lA8Tgb > svg")).click();
        driver.findElement(By.id("tw-source-text-ta")).sendKeys(input);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        assertThat(driver.findElement(By.id("tw-target-text")).getText(), is(translate));
    }
}
